name: EditorAutoPush

on:
  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - ".github/workflows/EditorAutoPush.yml"

jobs:
  EditorAutoPush:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        platform: [StandaloneOSX, StandaloneWindows64, iOS, Android]
    steps:
      # DEBUG用情報
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2
        with:
          lfs: true
          ref: ${{ github.head_ref }}
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-build-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-build-${{ matrix.targetPlatform }}-
            Library-build-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2020 }}
          # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }} 
          # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }} 
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          buildMethod: BuildCI.CompileErrorCheckCMD
          targetPlatform: ${{ matrix.platform }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: autocommit
        with:
          commit_message: "[GithubActions] AutoUpdate"
        continue-on-error: true
      - name: "Run if Commited have been detected"
        if: steps.autocommit.outcome == 'failure'
        run: echo "Parallel Commited"