name: EditorAutoPush

on:
  push:
    # branches:
    #   - "master"
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - ".github/workflows/EditorAutoPush.yml"

jobs:
  EditorAutoPush:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        platform: [StandaloneOSX, StandaloneWindows64, iOS, Android]
    steps:
      # DEBUG用情報
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2
        with:
          lfs: true
          ref: ${{ github.head_ref }}
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.platform }}
          restore-keys: Library-${{ matrix.platform }}
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2020 }}
          # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }} 
          # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }} 
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          buildMethod: BuildCI.CompileErrorCheckCMD
          targetPlatform: ${{ matrix.platform }}
      # - name: Diff
      #   id: diff
      #   run: |
      #     git add -N -v .
      #     git diff --name-only --exit-code
      #   continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[GithubActions] AutoUpdate"
      # - name: commit & push
      #   if: steps.diff.outcome == 'failure'
      #   run: |
      #     set -x
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add -v .
      #     git commit --author "$AUTHOR" -m "[GithubActions] AutoUpdate"
      #     git push